builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

checksum:
  name_template: "checksums.txt"

archives:
  - name_template: "git-sync-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

brews:
  - name: git-sync
    description: Updates your branches
    homepage: https://github.com/arbourd/git-sync

    conflicts:
      - git-extras
      - git-sync

    folder: Formula

    repository:
      owner: arbourd
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"

    commit_author:
      name: Dylan Arbour
      email: arbourd@users.noreply.github.com
