name: test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - run: go mod download
      - run: go build -o git-sync .

      - uses: actions/checkout@v3
        with:
          repository: arbourd/git-get
          fetch-depth: 1
          path: git-get
      - run: cd git-get && ../git-sync
