name: release

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
         fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  bump:
    name: Bump Homebrew formula
    runs-on: ubuntu-latest

    steps:
      - uses: mislav/bump-homebrew-formula-action@v1
        if: "!contains(github.ref, '-')" # skip prereleases
        with:
          formula-name: git-sync
          homebrew-tap: arbourd/homebrew-tap
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
